kind: pipeline
type: docker
name: bookmarkPublish

trigger:
  branch:
    - main

clone:
  disable: true

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: devHost
      port: 22
      user: root
      key:
        from_secret: privateSsh
      timeout: 3m
      script:
        - cd /root/qieziStatistics && git pull && bash build.sh && syncFile.sh
